name: CI/CD pipeline

on: 
    push:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm list
        



